AWSTemplateFormatVersion : '2010-09-09'
Transform:
    - Name: AWS::Serverless-2016-10-31
Description: A time application.

Outputs:
    ExecutionUrl:
        Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/time

Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.7
      InlineCode: | 
        from datetime import datetime

        def handler(event, context):
            eastern_time = datetime.now()
            return {
                'statusCode': 200,
                'body': "{}".format(eastern_time)
                
            }
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /time
            Method: GET