AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.

Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.7
      InlineCode: | 
        from datetime import datetime

        def handler(event, context):
            eastern_time = datetime.now()
            return {
                'statusCode': 200,
                'body': "<h1>The time in UTC is {}</h1>".format(eastern_time)
                
            }
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /time
            Method: GET
            RestApiId: 
                Ref: MyApi